const backOfCards = [
  {
    cardName: 'Start',
    type: 'Event',
    details: 'When a player passes start they receive 200M',
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Parker St.',
    color: 'brown',
    type: 'Property',
    price: 60,
    rent: 2,
    details: 'This property can be purchased. If already owned, the player who lands on the property must pay rent to the owner.',
    mortgage: 30,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chest',
    clicked: false,
  },
  {
    cardName: 'Tyne St.',
    color: 'brown',
    type: 'Property',
    price: 60,
    rent: 4,
    details: 'This property can be purchased. If already owned, the player who lands on the property must pay rent to the owner.',
    mortgage: 30,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Income Tax',
    details: 'If 1 owned, rent equals 4 times dice roll \n If 2 owned, rent equals 10 times dice roll',
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Reading Railroad',
    price: 200,
    details1: 'If 1 owned $25',
    details2: 'If 2 owned $50',
    details3: 'If 3 owned $100',
    details4: 'If 4 owned $200',
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Brighton Vale',
    color: 'lightblue',
    price: 100,
    rent: 6,
    mortgage: 50,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chance',
    clicked: false,
  },
  {
    cardName: 'Granary Vale',
    color: 'lightblue',
    price: 100,
    rent: 6,
    mortgage: 50,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Burford Vale',
    color: 'lightblue',
    price: 120,
    rent: 8,
    mortgage: 60,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Jail',
    clicked: false,
  },
  {
    cardName: 'Holden Fold',
    color: 'pink',
    price: 140,
    rent: 10,
    mortgage: 70,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Electric Company',
    details: 'If one "Utility" is owned rent is 4 times amount shown on dice. \n If both "Utilities" are owned rent is 10 times amount shown on dice',
    mortgage: 75,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Mere Fold',
    color: 'pink',
    price: 140,
    rent: 10,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Hedger Fold',
    color: 'pink',
    price: 160,
    rent: 12,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Pennsylvania Railroad',
    color: 'railroad',
    price: 200,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Danthorpe Lodge',
    color: 'orange',
    price: 180,
    rent: 14,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Chance',
    clicked: false,
  },
  {
    cardName: 'Rockingham Lodge',
    color: 'orange',
    price: 180,
    rent: 14,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Aveling Lodge',
    color: 'orange',
    price: 200,
    rent: 16,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Free Parking',
    clicked: false,
  },
  {
    cardName: 'Brambleberry Lane',
    color: 'red',
    price: 220,
    rent: 18,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chance',
  },
  {
    cardName: 'Guildford Lane',
    color: 'red',
    price: 220,
    rent: 18,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Albany Lane',
    color: 'red',
    price: 240,
    rent: 20,
    clicked: false,
    ownedBy: false,
  },
  {
    cardName: 'Short Line',
    color: 'railroad',
    price: 200,
    clicked: false,
  },
  {
    cardName: 'Elms Villas',
    color: 'yellow',
    price: 260,
    rent: 22,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Keepers Villas',
    color: 'yellow',
    price: 260,
    rent: 22,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Water Works',
    details: 'If one "Utility" is owned rent is 4 times amount shown on dice. \n If both "Utilities" are owned rent is 10 times amount shown on dice',
    mortgage: 75,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Moorcraft Villas',
    color: 'yellow',
    price: 280,
    rent: 24,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Go to jail',
    clicked: false,
  },
  {
    cardName: 'Whilworth Gardens',
    color: 'green',
    price: 300,
    rent: 26,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Brock Gardens',
    color: 'green',
    price: 300,
    rent: 26,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'Chest',
    clicked: false,
  },
  {
    cardName: 'Fair Gardens',
    color: 'green',
    price: 320,
    rent: 28,
    ownedBy: false,
    clicked: false,
  },
  {
    cardName: 'B. & O. Railroad',
    color: 'railroad',
    price: 200,
    clicked: false,
  },
  {
    cardName: 'Chance',
    clicked: false,
  },
  {
    cardName: 'Hartington Avenue',
    color: 'blue',
    price: 350,
    rent: 35,
    ownedBy: false,
    clicked: false
  },
  {
    cardName: 'Luxury Tax',
    rent: 150,
    clicked: false,
  },
  {
    cardName: 'Meadowlands Avenue',
    color: 'blue',
    price: 400,
    rent: 50,
    ownedBy: false,
    clicked: false,
  },
];

export default backOfCards;
